// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKGVMrnoPi0S736AhG9YJJkpmQucFw7Pw',
    appId: '1:251131996048:web:47b1ab107e9af069cc7515',
    messagingSenderId: '251131996048',
    projectId: 'notility-5bc8d',
    authDomain: 'notility-5bc8d.firebaseapp.com',
    storageBucket: 'notility-5bc8d.appspot.com',
    measurementId: 'G-60SHF625K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLq11JmUXF822pm0wfprqCoz7T0HpIgpQ',
    appId: '1:251131996048:android:65d2481de626b61fcc7515',
    messagingSenderId: '251131996048',
    projectId: 'notility-5bc8d',
    storageBucket: 'notility-5bc8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gyaEGdWo8hfrd6xr16WsNUJSRVzkRUo',
    appId: '1:251131996048:ios:bb407a101b46fbd4cc7515',
    messagingSenderId: '251131996048',
    projectId: 'notility-5bc8d',
    storageBucket: 'notility-5bc8d.appspot.com',
    iosBundleId: 'com.example.notility',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gyaEGdWo8hfrd6xr16WsNUJSRVzkRUo',
    appId: '1:251131996048:ios:c6d4598ef0c91681cc7515',
    messagingSenderId: '251131996048',
    projectId: 'notility-5bc8d',
    storageBucket: 'notility-5bc8d.appspot.com',
    iosBundleId: 'com.example.notility.RunnerTests',
  );
}
